# Generated by Django 2.0.2 on 2018-04-06 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
